# <span style="color:black;"><strong>Transformar Variables Categóricas</strong></span>  

# <span style="color:black;"><strong>3. Label Encoding</strong></span> 

Transforma cada categoría de una variable en un valor numérico entero único, asignando un número distinto a cada etiqueta. Este método es apropiado para variables ordinales o aquellas en las que el modelo pueda interpretar una relación entre los valores codificados. No se recomienda para variables nominales sin orden, ya que puede inducir relaciones numéricas inexistentes entre las categorías  ([Pedregosa et al., 2011](https://jmlr.csail.mit.edu/papers/v12/pedregosa11a.html)).

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt

# Configuración de estilo
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (8,4)

# Crear dataset
df = pd.read_csv("../datos/dataset_depurado.csv", sep=";")


# Codificar la variable categórica 'fuel'
le = LabelEncoder()
df['Fuel_encoded'] = le.fit_transform(df['Fuel'])

print("\nDataFrame con 'Fuel' codificado:")
print(df)

# Mostrar el mapeo de categorías a números
mapeo = dict(zip(le.classes_, le.transform(le.classes_)))
print("\nMapeo de categorías:")
print(mapeo)



DataFrame con 'Fuel' codificado:
       price            km     Fuel  Gears  age  Previous_Owners  hp_kW  \
0      15770  56013.000000   Diesel      7    3                2     66   
1      14500  80000.000000  Benzine      7    2                1    141   
2      14640  83450.000000   Diesel      7    3                1     85   
3      14500  73000.000000   Diesel      6    3                1     66   
4      16790  16200.000000   Diesel      7    3                1     66   
...      ...           ...      ...    ...  ...              ...    ...   
15910  39950   1647.362609   Diesel      6    0                1    147   
15911  39885   9900.000000  Benzine      7    0                1    165   
15912  39875     15.000000   Diesel      6    0                1    146   
15913  39700     10.000000   Diesel      6    0                1    147   
15914  40999   1647.362609  Benzine      6    0                1    165   

       Inspection_new  Displacement_cc  Weight_kg  cons_comb  Fue

In [4]:

# Aplicar LabelEncoder
encoder = LabelEncoder()
df_encoded = encoder.fit_transform(df['Fuel'])

# Convertir a DataFrame para visualización
df_label = pd.DataFrame(df_encoded, columns=['Fuel_encoded'])

# Combinar con original para comparación
df_comparado = pd.concat([df, df_label], axis=1)

print("\nDatos después de aplicar Label Encoding:")
print(df_comparado)


Datos después de aplicar Label Encoding:
       price            km     Fuel  Gears  age  Previous_Owners  hp_kW  \
0      15770  56013.000000   Diesel      7    3                2     66   
1      14500  80000.000000  Benzine      7    2                1    141   
2      14640  83450.000000   Diesel      7    3                1     85   
3      14500  73000.000000   Diesel      6    3                1     66   
4      16790  16200.000000   Diesel      7    3                1     66   
...      ...           ...      ...    ...  ...              ...    ...   
15910  39950   1647.362609   Diesel      6    0                1    147   
15911  39885   9900.000000  Benzine      7    0                1    165   
15912  39875     15.000000   Diesel      6    0                1    146   
15913  39700     10.000000   Diesel      6    0                1    147   
15914  40999   1647.362609  Benzine      6    0                1    165   

       Inspection_new  Displacement_cc  Weight_kg  cons_c

In [7]:
# Revertir los valores codificados a sus etiquetas originales
df_decoded = df_encoded.copy()
for col in df_decoded.columns:
    le = label_encoders[col]
    df_decoded[col] = le.inverse_transform(df_decoded[col])

print("\nDatos revertidos a sus etiquetas originales:")
print(df_decoded)


Datos revertidos a sus etiquetas originales:
       Fuel
0    Diesel
1   Benzine
2  Electric
3   LPG/CNG


In [6]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Simulación de datos
df = pd.DataFrame({
    'Fuel': ['Diesel', 'Benzine', 'Electric', 'LPG/CNG']
})

# Codificación
label_encoders = {}
df_encoded = df.copy()
for col in df.columns:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Decodificación
df_decoded = df_encoded.copy()
for col in df_decoded.columns:
    le = label_encoders[col]
    df_decoded[col] = le.inverse_transform(df_decoded[col])

print("\nOriginal:")
print(df)
print("\nCodificado:")
print(df_encoded)
print("\nDecodificado:")
print(df_decoded)


Original:
       Fuel
0    Diesel
1   Benzine
2  Electric
3   LPG/CNG

Codificado:
   Fuel
0     1
1     0
2     2
3     3

Decodificado:
       Fuel
0    Diesel
1   Benzine
2  Electric
3   LPG/CNG


<div style="background-color:#fff9c4; padding:15px; border-radius:8px; font-size:17px;"> 
<b></b>

### **Revertir la codificación**

| Técnica             | Tipo de codificación | Línea de código para revertir              |
|---------------------|----------------------|--------------------------------------------|
| `LabelEncoder`      | Nominal (entero)     | `LabelEncoder.inverse_transform()`         |
| `OrdinalEncoder`    | Ordinal (entero)     | `OrdinalEncoder.inverse_transform()`       |
| `OneHotEncoder`     | Nominal (binario)    | `OneHotEncoder.inverse_transform()`        |
| `pd.get_dummies()`  | Nominal (binario)    | *No disponible directamente*               |

</div>


# <span style="color:black;"><strong>4. Count Enconding</strong></span> 

Sustituye cada categoría por su **frecuencia de aparición** o su **proporción en el conjunto de datos**, conservando información sobre su relevancia o representatividad.  
Se utiliza cuando existen **muchas categorías** o clases desbalanceadas.

<p align="center">
    <img src="Local\imgs\U4\count-encoding.jpg" alt="count-encoding" width="700"  height=300">
</p>

Imagen tomada de [blog.dailydoseofds](https://blog.dailydoseofds.com/p/7-must-know-techniques-for-encoding).

In [37]:
# DataFrame 
df = pd.DataFrame({
    'Color': ['Rojo', 'Azul', 'Verde', 'Rojo', 'Azul', 'Rojo'],
    'Forma': ['Circular', 'Cuadrado', 'Triangular', 'Circular', 'Triangular', 'Cuadrado']
})

print("Datos originales:")
print(df)

# Aplicar Count Encoding a cada columna categórica
df_count = df.copy()
for col in df_count.columns:
    counts = df_count[col].value_counts()
    df_count[col + '_count'] = df_count[col].map(counts)
    print(f"\n Count Encoding para '{col}':")
    print(df_count[[col, col + '_count']])

Datos originales:
   Color       Forma
0   Rojo    Circular
1   Azul    Cuadrado
2  Verde  Triangular
3   Rojo    Circular
4   Azul  Triangular
5   Rojo    Cuadrado

 Count Encoding para 'Color':
   Color  Color_count
0   Rojo            3
1   Azul            2
2  Verde            1
3   Rojo            3
4   Azul            2
5   Rojo            3

 Count Encoding para 'Forma':
        Forma  Forma_count
0    Circular            2
1    Cuadrado            2
2  Triangular            2
3    Circular            2
4  Triangular            2
5    Cuadrado            2


In [38]:
print("\n DataFrame final con Count Encoding:")
print(df_count)


 DataFrame final con Count Encoding:
   Color       Forma  Color_count  Forma_count
0   Rojo    Circular            3            2
1   Azul    Cuadrado            2            2
2  Verde  Triangular            1            2
3   Rojo    Circular            3            2
4   Azul  Triangular            2            2
5   Rojo    Cuadrado            3            2


In [40]:
import category_encoders as ce

encoder = ce.CountEncoder()
df_encoded = encoder.fit_transform(df)

print(df_encoded)


   Color  Forma
0      3      2
1      2      2
2      1      2
3      3      2
4      2      2
5      3      2


<div style="background-color:#fff9c4; padding:15px; border-radius:8px; font-size:17px;"> 
<b></b>

| Aspecto       | Detalle                                                                 |
|---------------|-------------------------------------------------------------------------|
| **Ventajas**  | - Fácil de implementar con `pandas` o `category_encoders`.<br>- Reduce la dimensionalidad comparado con One-Hot Encoding.<br>- Funciona bien con modelos basados en árboles como Random Forest o XGBoost.<br>- No introduce orden artificial como Label Encoding. |
| **Desventajas** | - Puede inducir sesgo si las frecuencias están correlacionadas con la variable objetivo.<br>- No es interpretable directamente (los valores no representan magnitudes reales).<br>- No maneja bien categorías nuevas si no se actualiza el mapeo.<br>- No es adecuado para modelos lineales sin normalización. |              |

</div>


# <span style="color:black;"><strong>5. Binary Encoding</strong></span>

El **Binary Encoding** es una técnica que combina las ventajas de *Label Encoding* y *One-Hot Encoding* para representar variables categóricas de manera **más compacta y eficiente**.  
Cada categoría se transforma primero en un número entero y luego en su **equivalente binario**, donde cada bit se distribuye en columnas separadas.

Este método es especialmente útil cuando existen **muchas categorías únicas**, ya que **reduce la dimensionalidad** del conjunto de datos sin perder completamente la información de las categorías originales.  
Se aplica con frecuencia en **modelos de aprendizaje automático tradicionales** que requieren **entradas numéricas compactas** o en contextos donde *One-Hot Encoding* resulta ineficiente ([Géron, 2023](https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967/)).


<p align="center">
    <img src="Local\imgs\U4\binary.jpg" alt="binary" width="700"  height=300">
</p>

Imagen tomada de [blog.dailydoseofds](https://blog.dailydoseofds.com/p/7-must-know-techniques-for-encoding).

In [41]:
import pandas as pd
import category_encoders as ce

# Dataframe
df = pd.DataFrame({
    'Color': ['green', 'red', 'black', 'orange']
})

print(" Datos originales:")
print(df)

# Aplicar Binary Encoding
encoder = ce.BinaryEncoder(cols=['Color'])
df_encoded = encoder.fit_transform(df)

print("\n Datos codificados con Binary Encoding:")
print(df_encoded)


 Datos originales:
    Color
0   green
1     red
2   black
3  orange

 Datos codificados con Binary Encoding:
   Color_0  Color_1  Color_2
0        0        0        1
1        0        1        0
2        0        1        1
3        1        0        0


In [46]:
# DataFrame
df = pd.DataFrame({
    'Color': ['green', 'red', 'black', 'orange'],
    'Forma': ['circle', 'square', 'triangle', 'circle']
})

print("Datos originales:")
print(df)

# Aplicar Binary Encoding a múltiples columnas
encoder = ce.BinaryEncoder(cols=['Color', 'Forma'])
df_encoded = encoder.fit_transform(df)

print("\nDatos codificados con Binary Encoding:")
print(df_encoded)


Datos originales:
    Color     Forma
0   green    circle
1     red    square
2   black  triangle
3  orange    circle

Datos codificados con Binary Encoding:
   Color_0  Color_1  Color_2  Forma_0  Forma_1
0        0        0        1        0        1
1        0        1        0        1        0
2        0        1        1        1        1
3        1        0        0        0        1


# <span style="color:black;"><strong>6. Embeddings Categóricos</strong></span>

En entornos de **aprendizaje profundo**, las categorías pueden representarse mediante **vectores densos** que capturan relaciones semánticas entre ellas.  
Este enfoque se usa ampliamente en **procesamiento del lenguaje natural (NLP)** y **sistemas de recomendación** ([Géron, 2023](https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967/)).

<p align="center">
    <img src="Local\imgs\U4\one_hot_hot_dog_embedding.png" alt="one_hot_hot_dog_embedding" width="700"  height=300">
</p>

Imagen tomada de [blog.dailydoseofds](https://developers.google.com/machine-learning/crash-course/embeddings/obtaining-embeddings?hl=es-419).

In [50]:
import torch
import torch.nn as nn

# Supongamos que tenemos 4 colores: green, red, black, orange
# Asignamos un índice entero a cada uno
color_to_index = {'green': 0, 'red': 1, 'black': 2, 'orange': 3}
color_indices = torch.tensor([color_to_index[c] for c in ['green', 'red', 'black', 'orange']])

# Creamos una capa de embedding: 4 categorías → vectores de dimensión 3
embedding_layer = nn.Embedding(num_embeddings=4, embedding_dim=3)

# Obtenemos los embeddings
embedded_colors = embedding_layer(color_indices)

print("Índices de colores:", color_indices)
print("Embeddings generados:")
print(embedded_colors)


Índices de colores: tensor([0, 1, 2, 3])
Embeddings generados:
tensor([[ 0.1628, -1.1315,  0.0254],
        [-1.2718,  0.7218, -1.6844],
        [-0.4428,  0.5568,  0.6037],
        [-0.8426, -0.7367,  0.1369]], grad_fn=<EmbeddingBackward0>)


In [51]:
# Datos
color_vocab = {'green': 0, 'red': 1, 'black': 2, 'orange': 3}
shape_vocab = {'circle': 0, 'square': 1, 'triangle': 2}

# Simulamos un batch de 4 ejemplos
color_input = torch.tensor([color_vocab[c] for c in ['green', 'red', 'black', 'orange']])
shape_input = torch.tensor([shape_vocab[s] for s in ['circle', 'square', 'triangle', 'circle']])

# Capas de embedding para cada variable
color_embedding = nn.Embedding(num_embeddings=4, embedding_dim=3)
shape_embedding = nn.Embedding(num_embeddings=3, embedding_dim=2)

# Aplicar embeddings
color_embedded = color_embedding(color_input)
shape_embedded = shape_embedding(shape_input)

# Concatenar los embeddings
combined = torch.cat([color_embedded, shape_embedded], dim=1)

print(" Embedding de Color:")
print(color_embedded)

print("\n Embedding de Forma:")
print(shape_embedded)

print("\n Embedding combinado:")
print(combined)


 Embedding de Color:
tensor([[-0.6649, -0.9860, -0.2435],
        [-1.4977, -1.1300,  0.2240],
        [ 0.7493, -0.3895,  0.9163],
        [ 0.8433, -0.2881, -0.9913]], grad_fn=<EmbeddingBackward0>)

 Embedding de Forma:
tensor([[-0.9036,  0.8219],
        [ 1.3459,  0.7084],
        [-1.2374,  0.5422],
        [-0.9036,  0.8219]], grad_fn=<EmbeddingBackward0>)

 Embedding combinado:
tensor([[-0.6649, -0.9860, -0.2435, -0.9036,  0.8219],
        [-1.4977, -1.1300,  0.2240,  1.3459,  0.7084],
        [ 0.7493, -0.3895,  0.9163, -1.2374,  0.5422],
        [ 0.8433, -0.2881, -0.9913, -0.9036,  0.8219]], grad_fn=<CatBackward0>)


<div style="background-color:#fff9c4; padding:15px; border-radius:8px; font-size:17px;"> 
<b></b>

| Aspecto                         | Descripción                                                                 |
|----------------------------------|------------------------------------------------------------------------------|
| **Uso principal**               | Representar categorías como vectores densos de números reales.              |
| **Tipo de codificación**        | Aprendida durante el entrenamiento; no fija como One-Hot o Label Encoding.  |
| **Salida**                      | Matriz de vectores (por ejemplo, cada categoría → vector de dimensión 3, 4, etc.). |
| **Ventajas**                    | - Captura relaciones semánticas entre categorías.<br>- Reduce dimensionalidad.<br>- Escalable para miles de categorías.<br>- Ideal para redes neuronales y modelos tabulares profundos. |
| **Desventajas**                 | - Requiere entrenamiento supervisado.<br>- No interpretable directamente.<br>- No compatible con modelos clásicos como árboles o regresión lineal sin adaptación. |
| **Manejo de múltiples columnas**| Se necesita una capa de embedding por cada variable categórica.             |
| **Manejo de valores desconocidos** | Puede manejarse con un índice especial (por ejemplo, "unknown" o padding).  |
| **Recomendación**              | Úsalo en modelos de deep learning cuando hay muchas categorías o relaciones complejas. |


</div>

# <span style="color:black;"><strong>Comparación</strong></span>

| Característica                  | Label Encoding                        | One-Hot Encoding                          | Embeddings Categóricos                     |
|----------------------------------|----------------------------------------|--------------------------------------------|---------------------------------------------|
| **Tipo de salida**              | Entero por categoría (0, 1, 2...)      | Vector binario (una columna por categoría) | Vector denso de números reales              |
| **Dimensión generada**          | 1 columna                              | n columnas (n = número de categorías)       | Tú defines la dimensión (ej. 3, 4, 8...)     |
| **Captura relaciones semánticas** | ❌ No                                   | ❌ No                                       | ✅ Sí (aprendidas durante entrenamiento)     |
| **Adecuado para modelos clásicos** | ✅ Sí                                   | ✅ Sí                                       | ❌ No (requiere redes neuronales)            |
| **Escalabilidad con muchas categorías** | ✅ Buena                             | ❌ Mala (genera más columnas)               | ✅ Excelente                                 |
| **Interpretabilidad**           | ✅ Fácil                                | ✅ Fácil                                    | ❌ Difícil                                   |
| **Orden implícito**             | ✅ Sí (aunque puede ser artificial)     | ❌ No                                       | ❌ No                                        |
| **Uso típico**                  | Árboles, regresión lineal              | Árboles, regresión, redes simples           | Deep learning tabular, NLP, recomendadores  |
